name = "Rally NTM"
author = "Rally and Eset"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "05b30cc483a7f7066d189c1521cbdf37138343a1d2b4d938198c6a5b5f4b3b2b"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
unsup = "1.1.5"
