name = "Rally NTM"
author = "Rally and Eset"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "374f04359e1b5b89d704e2ae1197ffabb16249b2d14ea1ef825baf2e065c5733"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
unsup = "1.1.5"
