name = "Rally NTM"
author = "Rally and Eset"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f8b8d26cd1a3b53f993237c4a0414a320fbac14511e2070379ced54ae277a0f0"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
unsup = "1.1.5"
