name = "Rally NTM"
author = "Rally and Eset"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8d29326fded26a0e297cd38088a486db490bb0611af284e033df8115fafce673"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
unsup = "1.1.5"
