name = "Ancient's Industria"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d15e92264f7fc8f49d8387dc88a4e0df04036540fa3aaa399ae81e919dc32da"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.193"
unsup = "1.1.5"
