hash-format = "sha256"

[[files]]
file = "mods/biolith.pw.toml"
hash = "e28be9e32294f80bf7be78a1eca5ad0cdc73e2fa636f9f0561d746b4fd2a1fe5"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "d6043c928c34ce1f4ada544a49193f95c281665cf88d4931e73370ea02870bed"
metafile = true

[[files]]
file = "mods/data-essence.pw.toml"
hash = "5b97fcdce5721b4bd5d60be3562eeeca8e8d7d84ec67e2ca635fafc807eb745e"
metafile = true

[[files]]
file = "mods/databank.pw.toml"
hash = "e6e87243dc5df3696ef2859d2c0c0891909e63544ac4eaaa3a1c8effa68ade56"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
hash = "d3c9b48d7caa2ed964e5d1a4dab1da5655c63f0a7e4a59231c4369be7ffc30e1"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
hash = "44abae510395f12f9ea97b8296b2f72e25f18b9f3f2cc0ee42c0d9afd73fe0b3"
metafile = true

[[files]]
file = "mods/irons-spells-n-spellbooks.pw.toml"
hash = "3d52adcc60da1d61c5a9a09e04e87e2f70880da8183685e454dbfa4e4d84f567"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "e7d3f7e0472ba9a3ef946fa5defcb157e4126636e603c2306d4ad6065936d5e2"
metafile = true

[[files]]
file = "mods/lithostitched.pw.toml"
hash = "f8edc1d5fadb1b65f8f869893ec637ec8a5e5f92fb0a7f140e9e62977668f895"
metafile = true

[[files]]
file = "mods/natural-philosophy.pw.toml"
hash = "e7ec4f2d19874a0910c8ceea5af7d1b31e8addcba218630c1efc168e7b575485"
metafile = true

[[files]]
file = "mods/no-mans-land.pw.toml"
hash = "095d580949dee2ea02c874d7fb73231786e25f7aacbc5a90ae597498ef26f74c"
metafile = true

[[files]]
file = "mods/tmrv.pw.toml"
hash = "9a2c112447329f1daea6cda77d68d3cdf7f292ae9e72f69adbfc18cb18ab1eeb"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "9d76c3683cfea5c5976823a000eacc9944db9f097894356d2a029cf36642ffa4"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "9b8940ac83dde84cfc59860c6544a4b1194e635786c26bd47dc15eee79e63598"
metafile = true
