hash-format = "sha256"

[[files]]
file = "config/MouseTweaks.cfg"
hash = "4069ce1a439d8c37453c1b1e9f2037e0942674c7e48723a39b37eab245792ad4"

[[files]]
file = "config/create-client.toml"
hash = "e20f6769fd946b918f24cfd54a422a599faa43394ee9a33012e645102a366da3"

[[files]]
file = "config/create-common.toml"
hash = "2e77b1d93b40ce3f381ad7eb2a9e6d7148de917518be5c2616939a4369c4b140"

[[files]]
file = "config/create-server.toml"
hash = "d064439be080c815a9fe7d53f01f46a17e959fb897aa8f0bb41284ecb88f15dc"

[[files]]
file = "config/curios-client.toml"
hash = "8af475d222d452c40b548db89c8956f3e4d1e2aaf729464e3065f029936b3e0d"

[[files]]
file = "config/curios-common.toml"
hash = "9f00a6b9904cf63a36c0c72f8346642962d538aaa78b59943b9de60dda82e6d0"

[[files]]
file = "config/curios-server.toml"
hash = "10002ec9366c21b5a90ca6830abc262e35ab07cfa26bb4a3df1d812930b13981"

[[files]]
file = "config/databank-client.toml"
hash = "458b1021022143ad3213af9bd7ea7ac1b1ef5f10e811ef2df5081719ec5791f5"

[[files]]
file = "config/datanessence-client.toml"
hash = "ae2c90a1bbd9c5a7fcdebf540361243c63dfc582de97c980936e8fed844f5640"

[[files]]
file = "config/datanessence.toml"
hash = "ece72c4f31caaa92b2b01ce981ed4a4b81c074f5f2b4fcaebd99c73181ad4c22"

[[files]]
file = "config/embeddium-mixins.properties"
hash = "708750dc530ed52462185c7b1421291db8b292a350e164daaad437ba6f4fe4ef"

[[files]]
file = "config/embeddium-options.json"
hash = "2e45fad8b1f64480f223f2c48be441d2e6d9768581fce2f247483574335b383c"

[[files]]
file = "config/farmersdelight-client.toml"
hash = "0aef81f57e2afd3906cf175407fa0725c3186eae76f0708a87454eaa57c9d72c"

[[files]]
file = "config/farmersdelight-common.toml"
hash = "791910f203df5c230f75bdcd5948023d44a428e3f73ca30dbe317b11ed8f59e4"

[[files]]
file = "config/figura.json"
hash = "45d1b9d9bf59fbd6a384fe8a7d1db75f7364276e17819f738c670202be5d4fd4"

[[files]]
file = "config/flywheel-client.toml"
hash = "49414280350d38397bb99dc9f721e07e8d3d17920094455f08ae10079d460d9a"

[[files]]
file = "config/fml.toml"
hash = "cc59fb1039726fda3ab1eb69b06d9b9aebb7496604ea579cfb735bc5377e7825"

[[files]]
file = "config/global_packs.toml"
hash = "e521baea8cde5a275585c7063fa3272b79a303c73e4efb1d509a638914e1299e"

[[files]]
file = "config/irons_spellbooks-client.toml"
hash = "3fa2598d7de323567c85ebf73380be870d051381615daecc386d6366b4d7b9d4"

[[files]]
file = "config/irons_spellbooks-server.toml"
hash = "8a5f5d57d8eff6cc8fdc9b2287618badcca5924908342b388c7987552772361a"

[[files]]
file = "config/jade/hide-blocks.json"
hash = "309df4ae96864c19eae41b646d58497c85a73b1fc3c584e772ef4d5822794baa"

[[files]]
file = "config/jade/hide-entities.json"
hash = "3741bb54a4535fb5a00fb0ee1f4386f3dd17834aebdf9e89c21fcd3307109709"

[[files]]
file = "config/jade/jade.json"
hash = "5754114a0a663b321793a61f741bafa70c2a6dd649657260cdc096600763ad94"

[[files]]
file = "config/jade/plugins.json"
hash = "b3c0a9bd26fa5d8eb7c629595f2792399a83337bee40fa80c0434e9c31db1c4a"

[[files]]
file = "config/jade/sort-order.json"
hash = "588e23cba070bf54132635f162e8283e7d926b57ab168435da4ccd4bc743c0c6"

[[files]]
file = "config/jeimode.pw.toml"
hash = "43e2c27d77414fb75a56ff3c6185846017e9a9b060621d5f97a5e243ee321372"
metafile = true

[[files]]
file = "config/lithostitched.json"
hash = "d8a63933ec4757186a594debea59dd35724a0a895fe601b324f96217c28312df"

[[files]]
file = "config/mixed_litter-startup.toml"
hash = "800b25a803f416531dfec28d27bdacd700bbdfa5e0e06161a334f5c0017f5904"

[[files]]
file = "config/modonomicon-client.toml"
hash = "f7301ac5c174fd4958b6a7bbca7d6211da2f4ac83f85ef87e55461a2110f9044"

[[files]]
file = "config/moreoverlays.toml"
hash = "686e3b7bed301331bf8b66291ac8d384f5021c40f8ff48a895990af89330fb74"

[[files]]
file = "config/neoforge-client.toml"
hash = "8e2ca8579919103d3a0eb896b8ed187c6acdf4ceddb026830746c34593d3e489"

[[files]]
file = "config/neoforge-common.toml"
hash = "fe878a2717a145cd890621eac5b3be1e1fd656f7ff9abc6e8d53f670d37474c4"

[[files]]
file = "config/neoforge-server.toml"
hash = "b1e3b38d612295f8d9dfa0fbdb538a992b7a1a3b7a766c491b4e9fdf3823396f"

[[files]]
file = "config/nomansland-client.toml"
hash = "03f5f372a988cbf1d5d06fd2addc2cb41baf85fe3864fb06edc711eb2c99c210"

[[files]]
file = "config/nomansland-common.toml"
hash = "8b4853e583cd42e40efc29f1b908890704a052a4bc965de76d9f8a2cf2ac9ede"

[[files]]
file = "config/nomansland-startup.toml"
hash = "4f9cc6ff573131acf9e92638b8686d2cfcaafbececd4289d4b5b431a4e9cc697"

[[files]]
file = "config/openpartiesandclaims-server.toml"
hash = "6aa19617c6bbec9c5a93a7dc442add066897003835683c9c0be5ec8c910ab2e3"

[[files]]
file = "config/patchouli-client.toml"
hash = "d9a6d7cadb6d473cf087602d9866840d2bb7f2c16915267eb3f6fbf68d5d774d"

[[files]]
file = "config/ponder-client.toml"
hash = "f7892742494899f3d7169cbefd1969c7030f1555bfc277e0a0a8fc6b9160b053"

[[files]]
file = "config/standardmode.pw.toml"
hash = "bf53d7614e82ee557571a82a63969d524579b7aed9ad1800d663d28794fe96b1"
metafile = true

[[files]]
file = "config/theurgy-client.toml"
hash = "2f5489d182fe54cf1850e00d93b408777880933d1056fa8a556d49fe947a7828"

[[files]]
file = "config/theurgy-server.toml"
hash = "3b0fe87ab80d9607978832d8d8b59e4e2da0f4bbeea86223a267cacb5576d0c0"

[[files]]
file = "config/xaerominimap-common.txt"
hash = "771a844d13ab6c2ff99f14b8fd912d02c55a1a4104361692b740c3e596084f6f"

[[files]]
file = "config/xaerominimap.txt"
hash = "71cffe7689e579cdf95700b08791f8382f9ae4e9709c5f6f4addc736f145ab3e"

[[files]]
file = "config/xaerominimap_entities.json"
hash = "c63fa9862b71e4d7d39f0ba3c214ec8482c622d960574003eabe56dd021cbead"

[[files]]
file = "config/xaeropatreon.txt"
hash = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"

[[files]]
file = "config/xaeroworldmap-common.txt"
hash = "f02ca95d7246bd4b9c7de895c46108fff42fd5fcf9d56816b7bdba821597b58f"

[[files]]
file = "config/xaeroworldmap.txt"
hash = "6028733f967d0d0f6a80dd236d3dcc7d2446912c719ab9a7d3f83d8624d9b92d"

[[files]]
file = "mods/alchemancy.pw.toml"
hash = "f74de1fc4cd66c078e99405ca3fb69a43635d4318e0c3b5e4c8fbe36b0304417"
metafile = true

[[files]]
file = "mods/biolith.pw.toml"
hash = "e28be9e32294f80bf7be78a1eca5ad0cdc73e2fa636f9f0561d746b4fd2a1fe5"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "d6043c928c34ce1f4ada544a49193f95c281665cf88d4931e73370ea02870bed"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "36debf7653e95a855b4fedacc19027cf2e01960fc0b6d55ef2ffbffbcb455690"
metafile = true

[[files]]
file = "mods/data-essence.pw.toml"
hash = "5b97fcdce5721b4bd5d60be3562eeeca8e8d7d84ec67e2ca635fafc807eb745e"
metafile = true

[[files]]
file = "mods/databank.pw.toml"
hash = "e6e87243dc5df3696ef2859d2c0c0891909e63544ac4eaaa3a1c8effa68ade56"
metafile = true

[[files]]
file = "mods/ears.pw.toml"
hash = "b42ea604c46fc73d9474ebc9d6d3d64a1efe6b9d5df8512c71a86f820eb8a105"
metafile = true

[[files]]
file = "mods/embeddium.pw.toml"
hash = "778c42263b2ba7c9e73553bdcd70f48a3e485ba52b6a83474160d48be696b71f"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
hash = "d3c9b48d7caa2ed964e5d1a4dab1da5655c63f0a7e4a59231c4369be7ffc30e1"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
hash = "44abae510395f12f9ea97b8296b2f72e25f18b9f3f2cc0ee42c0d9afd73fe0b3"
metafile = true

[[files]]
file = "mods/figura.pw.toml"
hash = "a0d6c1c458975efd2a57b5d8d6920b0647a884cc77463be5716f93c3f0112cb5"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "960fb33c17aca9c635f99009c1f16d75c312d043e302a599f6ce8040452079e6"
metafile = true

[[files]]
file = "mods/globalpacks.pw.toml"
hash = "a7f2ae8ea415e95ce1a3518b66edcaf124d8903ff9101d07331f7fec92b3400f"
metafile = true

[[files]]
file = "mods/iron-chests.pw.toml"
hash = "89395dd9fcb8ae67889d991207cb95ed7158571c387dde88012853c5fa9ca3fb"
metafile = true

[[files]]
file = "mods/irons-spells-n-spellbooks.pw.toml"
hash = "3d52adcc60da1d61c5a9a09e04e87e2f70880da8183685e454dbfa4e4d84f567"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "e7d3f7e0472ba9a3ef946fa5defcb157e4126636e603c2306d4ad6065936d5e2"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "5d49dd7272a1418fabed10e3ef9b5c79c3bbb9205d83e79e301c16ad0a0e89e6"
metafile = true

[[files]]
file = "mods/lithostitched.pw.toml"
hash = "f8edc1d5fadb1b65f8f869893ec637ec8a5e5f92fb0a7f140e9e62977668f895"
metafile = true

[[files]]
file = "mods/modonomicon.pw.toml"
hash = "98e2cc1f476858e0e1549cd13e7069a6a379da2588d71f5fc151d3f2d4a20485"
metafile = true

[[files]]
file = "mods/more-overlays-updated.pw.toml"
hash = "aebb0584b057847e605301fac10e669613bf9c9215ed7cbe6f49e6047487c680"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "6bc414cc0f2d4c078fe83f384d786343f701f371d657c5279b5b0df1595804bd"
metafile = true

[[files]]
file = "mods/natural-philosophy.pw.toml"
hash = "e7ec4f2d19874a0910c8ceea5af7d1b31e8addcba218630c1efc168e7b575485"
metafile = true

[[files]]
file = "mods/neoauth.pw.toml"
hash = "8a36f6a5dcd8149c36ac7ad1c4dce76a997b814075033d406cbbacfe197de54f"
metafile = true

[[files]]
file = "mods/no-mans-land.pw.toml"
hash = "095d580949dee2ea02c874d7fb73231786e25f7aacbc5a90ae597498ef26f74c"
metafile = true

[[files]]
file = "mods/open-parties-and-claims.pw.toml"
hash = "9d4e4bd1007b5529b2b35439d00d74f0554f2bd8ae0d4d72aeab9d8063c60beb"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
hash = "04ba8a8c91a6c25c42321493a2d233762bb01169fac5fd834e434887cdbf8596"
metafile = true

[[files]]
file = "mods/playeranimator.pw.toml"
hash = "c83705becd548879473132552de960f9d5975fa0edaeeb2d4665a4e35457423e"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "0281ed9713f3141bdac363056a791845510e14761ea65b4b2813cf96d664b20a"
metafile = true

[[files]]
file = "mods/theurgy.pw.toml"
hash = "7075deaae99440ae282f460b6f2975abe2fe6f4595a38139bf385dce622d5661"
metafile = true

[[files]]
file = "mods/tmrv.pw.toml"
hash = "9a2c112447329f1daea6cda77d68d3cdf7f292ae9e72f69adbfc18cb18ab1eeb"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "9d76c3683cfea5c5976823a000eacc9944db9f097894356d2a029cf36642ffa4"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "9b8940ac83dde84cfc59860c6544a4b1194e635786c26bd47dc15eee79e63598"
metafile = true

[[files]]
file = "unsup.toml"
hash = "9a6f129f3163bbb8e0d0031bde72b3a231cbcce6fccdce9ae57a68953d1a2f88"
