hash-format = "sha256"

[[files]]
file = "mods/alchemancy.pw.toml"
hash = "f74de1fc4cd66c078e99405ca3fb69a43635d4318e0c3b5e4c8fbe36b0304417"
metafile = true

[[files]]
file = "mods/biolith.pw.toml"
hash = "e28be9e32294f80bf7be78a1eca5ad0cdc73e2fa636f9f0561d746b4fd2a1fe5"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "d6043c928c34ce1f4ada544a49193f95c281665cf88d4931e73370ea02870bed"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "36debf7653e95a855b4fedacc19027cf2e01960fc0b6d55ef2ffbffbcb455690"
metafile = true

[[files]]
file = "mods/data-essence.pw.toml"
hash = "5b97fcdce5721b4bd5d60be3562eeeca8e8d7d84ec67e2ca635fafc807eb745e"
metafile = true

[[files]]
file = "mods/databank.pw.toml"
hash = "e6e87243dc5df3696ef2859d2c0c0891909e63544ac4eaaa3a1c8effa68ade56"
metafile = true

[[files]]
file = "mods/ears.pw.toml"
hash = "b42ea604c46fc73d9474ebc9d6d3d64a1efe6b9d5df8512c71a86f820eb8a105"
metafile = true

[[files]]
file = "mods/embeddium.pw.toml"
hash = "778c42263b2ba7c9e73553bdcd70f48a3e485ba52b6a83474160d48be696b71f"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
hash = "d3c9b48d7caa2ed964e5d1a4dab1da5655c63f0a7e4a59231c4369be7ffc30e1"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
hash = "44abae510395f12f9ea97b8296b2f72e25f18b9f3f2cc0ee42c0d9afd73fe0b3"
metafile = true

[[files]]
file = "mods/figura.pw.toml"
hash = "a0d6c1c458975efd2a57b5d8d6920b0647a884cc77463be5716f93c3f0112cb5"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "960fb33c17aca9c635f99009c1f16d75c312d043e302a599f6ce8040452079e6"
metafile = true

[[files]]
file = "mods/globalpacks.pw.toml"
hash = "a7f2ae8ea415e95ce1a3518b66edcaf124d8903ff9101d07331f7fec92b3400f"
metafile = true

[[files]]
file = "mods/iron-chests.pw.toml"
hash = "89395dd9fcb8ae67889d991207cb95ed7158571c387dde88012853c5fa9ca3fb"
metafile = true

[[files]]
file = "mods/irons-spells-n-spellbooks.pw.toml"
hash = "3d52adcc60da1d61c5a9a09e04e87e2f70880da8183685e454dbfa4e4d84f567"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "e7d3f7e0472ba9a3ef946fa5defcb157e4126636e603c2306d4ad6065936d5e2"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "5d49dd7272a1418fabed10e3ef9b5c79c3bbb9205d83e79e301c16ad0a0e89e6"
metafile = true

[[files]]
file = "mods/lithostitched.pw.toml"
hash = "f8edc1d5fadb1b65f8f869893ec637ec8a5e5f92fb0a7f140e9e62977668f895"
metafile = true

[[files]]
file = "mods/modonomicon.pw.toml"
hash = "98e2cc1f476858e0e1549cd13e7069a6a379da2588d71f5fc151d3f2d4a20485"
metafile = true

[[files]]
file = "mods/more-overlays-updated.pw.toml"
hash = "aebb0584b057847e605301fac10e669613bf9c9215ed7cbe6f49e6047487c680"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "6bc414cc0f2d4c078fe83f384d786343f701f371d657c5279b5b0df1595804bd"
metafile = true

[[files]]
file = "mods/natural-philosophy.pw.toml"
hash = "e7ec4f2d19874a0910c8ceea5af7d1b31e8addcba218630c1efc168e7b575485"
metafile = true

[[files]]
file = "mods/neoauth.pw.toml"
hash = "8a36f6a5dcd8149c36ac7ad1c4dce76a997b814075033d406cbbacfe197de54f"
metafile = true

[[files]]
file = "mods/no-mans-land.pw.toml"
hash = "095d580949dee2ea02c874d7fb73231786e25f7aacbc5a90ae597498ef26f74c"
metafile = true

[[files]]
file = "mods/open-parties-and-claims.pw.toml"
hash = "9d4e4bd1007b5529b2b35439d00d74f0554f2bd8ae0d4d72aeab9d8063c60beb"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
hash = "04ba8a8c91a6c25c42321493a2d233762bb01169fac5fd834e434887cdbf8596"
metafile = true

[[files]]
file = "mods/playeranimator.pw.toml"
hash = "c83705becd548879473132552de960f9d5975fa0edaeeb2d4665a4e35457423e"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "0281ed9713f3141bdac363056a791845510e14761ea65b4b2813cf96d664b20a"
metafile = true

[[files]]
file = "mods/theurgy.pw.toml"
hash = "7075deaae99440ae282f460b6f2975abe2fe6f4595a38139bf385dce622d5661"
metafile = true

[[files]]
file = "mods/tmrv.pw.toml"
hash = "9a2c112447329f1daea6cda77d68d3cdf7f292ae9e72f69adbfc18cb18ab1eeb"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "9d76c3683cfea5c5976823a000eacc9944db9f097894356d2a029cf36642ffa4"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "9b8940ac83dde84cfc59860c6544a4b1194e635786c26bd47dc15eee79e63598"
metafile = true

[[files]]
file = "unsup.toml"
hash = "c882f44c7eb84d17cb1058056ded8bb809ebbd2801f3cac37731e1a74483437f"
