name = "WR_Testpack"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "81a2d3996f31b8856cbe49f1294584def15e09015417f3860cc4193da652947e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
