name = "WR_Testpack"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aeb5013db67bdfde2f8101232ed3044e98f17a8ede10bca5c53098e7a2ea4287"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
