name = "WR_Testpack"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8fc7a75304b8c89568dbf2242556dcc5d7aec1ca39b11433eca3fc939b7daeda"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
unsup = "1.1.6"
