name = "WR_Testpack"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1319844e753cae2ae6e15083ea008cf49a40ae15bad34d035f5b5501e89a2ccb"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
