name = "WR_Testpack"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e6fe34d306f86eb9089acc824a55dc7d5679e45c20cfe66a18a0e8301d2cd7da"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
unsup = "1.1.6"
