name = "WR_Testpack"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e5ec76804c981ef1aaa11845973cd1f684685af690b50472167dec72596071ad"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
