name = "WR_Testpack"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "babbe6e463395151717b0a389b1445f383ea3b0081c9b6b2a066b04fa4e47c91"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
unsup = "1.1.6"
