name = "WR_Testpack"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0ffbbfec3850ee789e10befc7308fef3b8a0fec6302ec064f081aa9adef27e5e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
