name = "WR_Testpack"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a51b2c60dafa5e5f4feb4096e6c0aec5eb8eb3751a89def26646e5c72a7d2811"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
unsup = "1.1.6"
