[flavor_groups.viewer]
name = "Recipe Viewer"
description = "Recipe viewer mod to use. EMI (with the TMRV compat layer) is more performant, more customizable and has more features, and allows faster load times by loading data on world load. JEI has more commonly used direct compatability instead of requiring a universal compat layer mod."
side = "both"
[[flavor_groups.viewer.choices]]
id = "viewer_emi"
name = "EMI+TMRV"
description = "Installs EMI and TMRV."
[[flavor_groups.viewer.choices]]
id = "viewer_jei"
name = "JEI"
description = "Installs JEI."
[[flavor_groups.viewer.choices]]
id = "viewer_emi_configed"
name = "EMI+TMRV - JEI edition"
description = "Installs EMI and TMRV with customized configs to make it look like JEI."

[flavor_groups.rendering]
name = "Rendering Mod"
description = "Rendering mod to use. Sodium is better and more effective, however it has occasional layer sorting issues. Embeddium does not."
side = "client"
[[flavor_groups.rendering.choices]]
id = "rendering_sodium"
name = "Sodium"
description = "Installs Sodium."
[[flavor_groups.rendering.choices]]
id = "rendering_embeddium"
name = "Embeddium"
description = "Installs Embeddium."
[[flavor_groups.rendering.choices]]
id = "rendering_none"
name = "No"
description = "Do not install a rendering mod."

[flavor_groups.ears]
name = "Ears"
description = "Uses the otherwise-blank space on a modern 64x64 skin in combination with alpha layer encoding to give extra features to your player model, such as ears, wings, a custom cape, breasts, a snout and more. Client only. No effect (other than seeing other players Ears skins) if you do not have an Ears skin. Client only."
side = "client"
[[flavor_groups.ears.choices]]
id = "ears_on"
name = "Yes"
description = "Installs Ears."
[[flavor_groups.ears.choices]]
id = "ears_off"
name = "No"
description = "Do not install Ears."

[flavor_groups.figura]
name = "Figura"
description = "Animation-capable player models that come directly from Blockbench, with near unlimited capabilities for customization. Client only."
side = "client"
[[flavor_groups.figura.choices]]
id = "figura_on"
name = "Yes"
description = "Installs Figura."
[[flavor_groups.figura.choices]]
id = "figura_off"
name = "No"
description = "Do not install Figura."

[flavor_groups.mousetweaks]
name = "Mouse Tweaks"
description = "It's Mouse Tweaks. Either you know what it does, or you're living under a rock."
side = "both"
[[flavor_groups.mousetweaks.choices]]
id = "mousetweaks_on"
name = "Yes"
description = "Installs Mouse Tweaks."
[[flavor_groups.mousetweaks.choices]]
id = "mousetweaks_off"
name = "No"
description = "Do not install Mouse Tweaks."

[flavor_groups.mud]
name = "More Overlays"
description = "Classical light and chunk overlays toggled with F7 and F9, just like NEIs used to be. Client only."
side = "client"
[[flavor_groups.mud.choices]]
id = "mud_on"
name = "Yes"
description = "Installs More Overlays."
[[flavor_groups.mud.choices]]
id = "mud_off"
name = "No"
description = "Do not install More Overlays."

[flavor_groups.neoauth]
name = "Neoauth"
description = "Reauthentication without closing the game. Client only."
side = "client"
[[flavor_groups.neoauth.choices]]
id = "neoauth_on"
name = "Yes"
description = "Installs Neoauth."
[[flavor_groups.neoauth.choices]]
id = "neoauth_off"
name = "No"
description = "Do not install Neoauth."


[metafile.emi]
flavors = ["viewer_emi", "viewer_emi_configed"]
[metafile.tmrv]
flavors = ["viewer_emi", "viewer_emi_configed"]
[metafile.jei]
flavors = "viewer_jei"
[metafile.sodium]
flavors = "rendering_sodium"
[metafile.embeddium]
flavors = "rendering_embeddium"
[metafile.ears]
flavors = "ears_on"
[metafile.figura]
flavors = "figura_on"
[metafile.mouse-tweaks]
flavors = "mousetweaks_on"
[metafile.more-overlays-updated]
flavors = "mud_on"
[metafile.neoauth]
flavors = "neoauth_on"