#Inventory sorter modules
[modules]
	#Sorting module
	sortingmodule = true
	#Wheel move module
	wheelmovemodule = false
	#Avoid conflicts with mousetweaks wheel moves
	dodgemousetweaks = false
